### ISSUE TITLE
[Suggest] Support multi-language

### ISSUE THREAD

**Issue by Cyl18** [bigbass1997/NotEnoughProduction#2]

**Comment by bigbass1997** [comment]
Every item and fluid has at least 3 variables: the quantity, the unlocalized name, and the localized name. The localized name is usually whatever the translation class provides for the ItemStack/FluidStack, but it doesn't always return a good value.

Since the program just takes in whatever the recipe file gives it, it should already support other languages. This would be a better suggestion for RecEx instead. However, even then, it won't be a high priority for quite a long time.
